dist: focal
matrix:
  include:
    - language: node_js
      node_js: node
      script:
        - commitlint-travis
    - language: go
      go: 1.x
      before_install:
        - cd api
      install:
        - go get -d -v ./...
      script:
        - go vet .
        - go test -coverprofile=coverage.txt -covermode=atomic ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      services: mongodb
    - language: node_js
      node_js: node
      before_install:
        - cd client
      install:
        - yarn global add codecov
        - yarn
      script:
        - yarn lint && yarn test --coverageDirectory=coverage && yarn build
      after_success:
        - codecov
      cache: yarn
