version: '3'
services:
  client:
    build: ./client/
    container_name: tg-client
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - PORT=3333
      - DATABASE=tagallery
      - DATABASE_HOST=tg-mongodb
  api:
    build: ./api/
    container_name: tg-api
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.0
    container_name: tg-mongodb
    volumes:
      - ./mongodb:/data/db
    command: mongod