version: '3'
services:
  web:
    build: ./client/
    ports:
      - "8080:8080"
    depends_on:
      - api
    volumes:
      - ./client/:/var/www/
  api:
    build: ./api/
    ports:
      - "3333:3333"
