version: '3'
services:
  client:
    build: ./client/
    container_name: tg-client
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - PORT=80
      - HOST=0
      - API_URL=tg-api
  api:
    build: ./api/
    container_name: tg-api
    ports:
      - "3333:3333"
    depends_on:
      - mongodb
    environment:
      - DATABASE_HOST=tg-mongodb
      - DATABASE=tagallery
      - DEBUG=false
      - PORT=3333
      - IMAGES=/tmp/images
    volumes:
      - ./images:/tmp/images
  mongodb:
    image: mongo:4
    container_name: tg-mongodb
    volumes:
      - ./mongodb:/data/db
    command: mongod
    ports:
      - "27017:27017"
