version: '3'
services:
  # client:
  #   build: ./client/
  #   container_name: tg-client
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - api
  #   volumes:
  #     - ./client/:/var/www/
  # api:
  #   build: ./api/
  #   container_name: tg-api
  #   ports:
  #     - "3333:3333"
  mongodb:
    image: mongo:4.0
    container_name: tg-mongodb
    volumes:
      - ./mongodb:/data/db
    ports:
        - 27017:27017
    command: mongod
